export const SliderData = [
  {
    image:
      'https://i.imgur.com/STMjjYZ.png'
  },
  {
    image:
      'https://i.imgur.com/ulgvVPT.png'
  },
  {
    image:
      'https://i.imgur.com/SMp0P2o.png'
  },
  {
    image:
      'https://i.imgur.com/zZHss2w.png'
  },
  {
    image:
      'https://i.imgur.com/R3hrzz0.png'
  }
];
